const mongoose = require("mongoose");
const { Schema } = mongoose;

const reactionSchema = new Schema(
  {
    /*
    THIS FIELD IS NOT NEEDED AND CREATES BUGS. IDS ARE AUTO GENERATED 
    FOR SUBDOCUMENTS IN MONGOOSE (UNLESS THEY ARE TURNED OFF USING THIS OPTION: { _id : false }). 
    INSTEAD OF USING THIS FIELD, I AM USING THE ID FIELD GENERATED BY MONGOOSE. IT IS MORE EFFICIENT.
*/
    //   reactionId: {
    //     type: Schema.Types.ObjectId,
    //     default: () => new Types.ObjectId(),
    //   },
    reactionBody: {
      type: String,
      required: true,
      max: [280, "Provided text must be less than 280 character"],
    },
    // make this a utility later to reduce redundancy
    createdAt: {
      type: Date,
      default: Date.now,
      get: (v) =>
        `${new Intl.DateTimeFormat("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }).format(v)} at ${new Intl.DateTimeFormat("en-US", {
          hour: "numeric",
          minute: "numeric",
        }).format(v)}`,
    },
    username: {
      type: String,
      required: true,
    },
  },
  {
    toJSON: {
      getters: true,
    },
  }
);

module.exports = reactionSchema;
