const mongoose = require("mongoose");
const { Schema, Types } = mongoose;

const reactionSchema = new Schema({
/*
    THIS FIELD IS NOT NEEDED AND CREATES BUGS. IDS ARE AUTO GENERATED 
    FOR SUBDOCUMENTS IN MONGOOSE (UNLESS THEY ARE TURNED OFF USING THIS OPTION: { _id : false }). 
    INSTEAD OF USING THIS FIELD, I AM USING THE ID FIELD GENERATED BY MONGOOSE. IT IS MORE EFFICIENT.
*/
//   reactionId: {
//     type: Schema.Types.ObjectId,
//     default: () => new Types.ObjectId(),
//   },
  reactionBody: {
    type: String,
    required: true,
    max: [280, "Provided text must be less than 280 character"],
  },
  createdAt: { 
    type: Date, 
    default: Date.now,
    // https://mongoosejs.com/docs/schematypes.html#getters
    get: v => new Intl.DateTimeFormat('en-US', options).format(v)
 },
  username: {
    type: String,
    required: true,
  },
});

module.exports = reactionSchema;
